project:
  type: book

book:
  title: "The Shape and Color of Politics"
  subtitle: "How citizens process political information and its consequences"
  author: 
    - name: Damon C. Roberts
      affiliations: 
        - id: cu
          name: M.A., University of Colorado Boulder
        - id: bsu
          name: B.S., Boise State University
      email: damon.charles.roberts@gmail.com
  date: today
  date-format: long
  chapters:
    - index.qmd
    - chapter_2/src/manuscript.qmd
    - chapter_3/src/chapter_3.qmd
    - chapter_4/src/chapter_4.qmd
    - chapter_5/src/conclusion.qmd
    - references.qmd
  appendices:
    - chapter_2/src/appendix.qmd
  output-file: "dcr_book_project"

bibliography: "assets/references.bib"

format:
  titlepage-pdf:
    documentclass: scrbook
    coverpage: titleauthor
    coverpage-bg-image: "./front_matter/assets/cover.jpeg"
    coverpage-theme:
      title-fontsize: 100
      author-fontstyle: ["textsc"]
      author-style: "plain"
      author-fontsize: 30
      author-align: "right"
      author-bottom: "2in"
      date-style: "none"
    fontsize: 12pt
    titlepage: "plain"
    titlepage-theme:
      author-style: "author-address"
      affiliation-style: "none"
      affiliation-sep: "newline"
      elements: ["\\titleblock","\\authorblock","Last Compiled: \\dateblock"]
    fig-pos: 'b'
    toc: true
    lof: true
    lot: true
    include-in-header: 
      text: |
        \usepackage{makeidx}
        \makeindex
        \usepackage{lscape}
        \newcommand{\blandscape}{\begin{landscape}}
        \newcommand{\elandscape}{\end{landscape}}
    include-after-body: 
      text: |
        \printindex
jupyter: python3
execute:
  echo: false
  cache: false
  warning: false
  message: false