project:
  type: book

book:
  title: "The Shape and Color of Politics"
  subtitle: "How citizens process political information and its consequences"
  author: "Damon C. Roberts"
  date: today
  chapters:
    - index.qmd
    - chapter_1.qmd
    - chapter_2.qmd
    - conclusion.qmd
    - references.qmd
  output-file: book

bibliography: ../../assets/references.bib

format:
  pdf:
    documentclass: scrreport


execute:
  echo: false